# Create a copy of this file for purposes, and don't commit it to your repository.

# =========REQUIRED FIELDS=========
# Your secret bot token.
bot_token: ENTER_BOT_TOKEN_HERE

# Your discord server ID
server_id: ENTER_SERVER_ID_HERE

# Channel IDs
feedback_channel_id: ENTER_FEEDBACK_CHANNEL_ID_HERE
attendance_channel_id: ENTER_ATTENDANCE_CHANNEL_ID_HERE

# ProBot's "user" ID
probot_id: ENTER_PROBOT_USER_ID_HERE

# Path to the Google Application Service Account Credentials File
google_service_account_creds: ENTER_CREDENTIALS_FILE_PATH_HERE

# URL to the MT tracker sheet
google_sheets_url: ENTER_SHEETS_URL_HERE
job_sheet_url: ENTER_JOB_SHEET_URL_HERE